from Main import function1, function2, Class1
import Main

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

function1()
function2()
obj = Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()
Main.function1()
Main.function2()
obj = Main.Class1()
obj.method()

if __annotations__:
    if obj isinstance % 2
